const words = [
   
];

const kanjiWords = [
    { "id": 751, "kanji": "駐車", "hiragana": "ちゅうしゃ", "meaning": "Đỗ xe" },
    { "id": 752, "kanji": "駐車場", "hiragana": "ちゅうしゃじょう", "meaning": "Bãi đỗ xe" },
    { "id": 753, "kanji": "無休", "hiragana": "むきゅう", "meaning": "Không nghỉ" },
    { "id": 754, "kanji": "無料", "hiragana": "むりょう", "meaning": "Miễn phí" },
    { "id": 755, "kanji": "無理", "hiragana": "むり", "meaning": "Cố sức, không hợp lý" },
    { "id": 756, "kanji": "無い", "hiragana": "ない", "meaning": "Không có, không tồn tại" },
    { "id": 757, "kanji": "満車", "hiragana": "まんしゃ", "meaning": "Đầy xe" },
    { "id": 758, "kanji": "満員", "hiragana": "まんいん", "meaning": "Đầy người" },
    { "id": 759, "kanji": "不満", "hiragana": "ふまん", "meaning": "Bất mãn" },
    { "id": 760, "kanji": "方向", "hiragana": "ほうこう", "meaning": "Phương hướng" },
    { "id": 761, "kanji": "向こう", "hiragana": "むこう", "meaning": "Phía bên kia" },
    { "id": 762, "kanji": "向かう", "hiragana": "むかう", "meaning": "Hướng về" },
    { "id": 763, "kanji": "禁止", "hiragana": "きんし", "meaning": "Cấm đoán" },
    { "id": 764, "kanji": "関心", "hiragana": "かんしん", "meaning": "Quan tâm" },
    { "id": 765, "kanji": "関する", "hiragana": "かんする", "meaning": "Liên quan đến" },
    { "id": 766, "kanji": "関係", "hiragana": "かんけい", "meaning": "Mối quan hệ" },
    { "id": 767, "kanji": "係", "hiragana": "かかり", "meaning": "Người phụ trách" },
    { "id": 768, "kanji": "無断", "hiragana": "むだん", "meaning": "Không được phép" },
    { "id": 769, "kanji": "断水", "hiragana": "だんすい", "meaning": "Cắt nước" },
    { "id": 770, "kanji": "断る", "hiragana": "ことわる", "meaning": "Từ chối" },
    { "id": 771, "kanji": "横断", "hiragana": "おうだん", "meaning": "Băng ngang qua (đường)" },
    { "id": 772, "kanji": "横断歩道", "hiragana": "おうだんほどう", "meaning": "Lối băng qua đường" },
    { "id": 773, "kanji": "横", "hiragana": "よこ", "meaning": "Ngang, bên cạnh, bên hông" },
    { "id": 774, "kanji": "押す", "hiragana": "おす", "meaning": "Ấn, nhấn" },
    { "id": 775, "kanji": "押し入れ", "hiragana": "おしいれ", "meaning": "Tủ chìm (âm tường)" },
    { "id": 776, "kanji": "押さえる", "hiragana": "おさえる", "meaning": "Nhấn giữ (nút), giữ lại" },
    { "id": 777, "kanji": "式", "hiragana": "しき", "meaning": "Nghi thức, kiểu cách" },
    { "id": 778, "kanji": "入学式", "hiragana": "にゅうがくしき", "meaning": "Lễ khai giảng, lễ nhập trường" },
    { "id": 779, "kanji": "数式", "hiragana": "すうしき", "meaning": "Công thức số" },
    { "id": 780, "kanji": "送信", "hiragana": "そうしん", "meaning": "Gửi (email...)" },
    { "id": 781, "kanji": "自信", "hiragana": "じしん", "meaning": "Tự tin" },
    { "id": 782, "kanji": "信じる", "hiragana": "しんじる", "meaning": "Tin vào (tin tưởng)" },
    { "id": 783, "kanji": "信用", "hiragana": "しんよう", "meaning": "Tin tưởng, tín nhiệm" },
    { "id": 784, "kanji": "信号", "hiragana": "しんごう", "meaning": "Đèn tín hiệu" },
    { "id": 785, "kanji": "号車", "hiragana": "ごうしゃ", "meaning": "Toa (tàu) số..." },
    { "id": 786, "kanji": "正確", "hiragana": "せいかく", "meaning": "Chính xác" },
    { "id": 787, "kanji": "確か", "hiragana": "たしか", "meaning": "Chính xác, chắc chắn" },
    { "id": 788, "kanji": "確かめる", "hiragana": "たしかめる", "meaning": "Xác nhận, kiểm tra" },
    { "id": 789, "kanji": "確認", "hiragana": "かくにん", "meaning": "Sự xác nhận" },
    { "id": 790, "kanji": "認める", "hiragana": "みとめる", "meaning": "Chấp nhận, cho phép" },
    { "id": 791, "kanji": "飛行場", "hiragana": "ひこうじょう", "meaning": "Sân bay" },
    { "id": 792, "kanji": "飛ぶ", "hiragana": "とぶ", "meaning": "Bay" },
    { "id": 793, "kanji": "非常", "hiragana": "ひじょう", "meaning": "Khẩn cấp, cấp bách" },
    { "id": 794, "kanji": "非常口", "hiragana": "ひじょうぐち", "meaning": "Cửa thoát hiểm" },
    { "id": 795, "kanji": "非常に", "hiragana": "ひじょうに", "meaning": "Rất, cực kỳ" },
    { "id": 796, "kanji": "日常", "hiragana": "にちじょう", "meaning": "Thường ngày, hằng ngày" },
    { "id": 797, "kanji": "正常", "hiragana": "せいじょう", "meaning": "Bình thường" },
    { "id": 798, "kanji": "階", "hiragana": "かい", "meaning": "Tầng..." },
    { "id": 799, "kanji": "階段", "hiragana": "かいだん", "meaning": "Cầu thang" },
    { "id": 800, "kanji": "段", "hiragana": "だん", "meaning": "Bậc, đoạn, giai đoạn" },
    { "id": 801, "kanji": "箱", "hiragana": "はこ", "meaning": "Cái hộp" },
    { "id": 802, "kanji": "ごみ箱", "hiragana": "ごみばこ", "meaning": "Thùng rác" },
    { "id": 803, "kanji": "危険", "hiragana": "きけん", "meaning": "Nguy hiểm" },
    { "id": 804, "kanji": "危ない", "hiragana": "あぶない", "meaning": "Nguy hiểm, nguy cấp" },
    { "id": 805, "kanji": "捨てる", "hiragana": "すてる", "meaning": "Vứt bỏ, ném đi" },
    { "id": 806, "kanji": "線", "hiragana": "せん", "meaning": "Tuyến, đường" },
    { "id": 807, "kanji": "番線", "hiragana": "ばんせん", "meaning": "Sân ga số..." },
    { "id": 808, "kanji": "面", "hiragana": "めん", "meaning": "Mặt, bề mặt" },
    { "id": 809, "kanji": "全面", "hiragana": "ぜんめん", "meaning": "Toàn diện, mọi mặt" },
    { "id": 810, "kanji": "画面", "hiragana": "がめん", "meaning": "Màn hình" },
    { "id": 811, "kanji": "方面", "hiragana": "ほうめん", "meaning": "Đi về hướng" },
    { "id": 812, "kanji": "普通", "hiragana": "ふつう", "meaning": "Bình thường, thông thường" },
    { "id": 813, "kanji": "各駅", "hiragana": "かくえき", "meaning": "Mỗi ga" },
    { "id": 814, "kanji": "各国", "hiragana": "かっこく", "meaning": "Các nước" },
    { "id": 815, "kanji": "各自", "hiragana": "かくじ", "meaning": "Mỗi người, cá nhân" },
    { "id": 816, "kanji": "目次", "hiragana": "もくじ", "meaning": "Mục lục" },
    { "id": 817, "kanji": "次回", "hiragana": "じかい", "meaning": "Lần sau, lần tiếp theo" },
    { "id": 818, "kanji": "快速", "hiragana": "かいそく", "meaning": "Tốc hành, nhanh" },
    { "id": 819, "kanji": "高速道路", "hiragana": "こうそくどうろ", "meaning": "Đường cao tốc" },
    { "id": 820, "kanji": "速度", "hiragana": "そくど", "meaning": "Tốc độ" },
    { "id": 821, "kanji": "速い", "hiragana": "はやい", "meaning": "Nhanh" },
    { "id": 822, "kanji": "通過", "hiragana": "つうか", "meaning": "Đi qua, vượt qua" },
    { "id": 823, "kanji": "過去", "hiragana": "かこ", "meaning": "Quá khứ" },
    { "id": 824, "kanji": "過ぎる", "hiragana": "すぎる", "meaning": "Quá (mức), vượt quá" },
    { "id": 825, "kanji": "地下鉄", "hiragana": "ちかてつ", "meaning": "Tàu điện ngầm" },
    { "id": 826, "kanji": "鉄道", "hiragana": "てつどう", "meaning": "Đường sắt, đường tàu" },
    { "id": 827, "kanji": "鉄", "hiragana": "てつ", "meaning": "Sắt, thép" },
    { "id": 828, "kanji": "指定", "hiragana": "してい", "meaning": "Chỉ định" },
    { "id": 829, "kanji": "指定席", "hiragana": "していせき", "meaning": "Chỗ ngồi đặt trước" },
    { "id": 830, "kanji": "指", "hiragana": "ゆび", "meaning": "Ngón (tay, chân)" },
    { "id": 831, "kanji": "指輪", "hiragana": "ゆびわ", "meaning": "Nhẫn" },
    { "id": 832, "kanji": "定休日", "hiragana": "ていきゅうび", "meaning": "Ngày nghỉ định kỳ" },
    { "id": 833, "kanji": "安定", "hiragana": "あんてい", "meaning": "Ổn định, yên ổn" },
    { "id": 834, "kanji": "不安定", "hiragana": "ふあんてい", "meaning": "Không ổn định" },
    { "id": 835, "kanji": "席", "hiragana": "せき", "meaning": "Chỗ ngồi" },
    { "id": 836, "kanji": "出席", "hiragana": "しゅっせき", "meaning": "Có mặt, tham dự" },
    { "id": 837, "kanji": "欠席", "hiragana": "けっせき", "meaning": "Vắng mặt" },
    { "id": 838, "kanji": "自由", "hiragana": "じゆう", "meaning": "Tự do" },
    { "id": 839, "kanji": "自由席", "hiragana": "じゆうせき", "meaning": "Chỗ ngồi tự do" },
    { "id": 840, "kanji": "理由", "hiragana": "りゆう", "meaning": "Lý do" },
    { "id": 841, "kanji": "番号", "hiragana": "ばんごう", "meaning": "Số, số hiệu" },
    { "id": 842, "kanji": "番", "hiragana": "ばん", "meaning": "Số..." },
    { "id": 843, "kanji": "窓", "hiragana": "まど", "meaning": "Cửa sổ" },
    { "id": 844, "kanji": "窓口", "hiragana": "まどぐち", "meaning": "Quầy tiếp nhận, cửa tiếp nhận" },
    { "id": 845, "kanji": "側", "hiragana": "がわ", "meaning": "Bên, phía" },
    { "id": 846, "kanji": "両側", "hiragana": "りょうがわ", "meaning": "Hai bên" },
    { "id": 847, "kanji": "窓側", "hiragana": "まどがわ", "meaning": "Bên cửa sổ" },
    { "id": 848, "kanji": "右側", "hiragana": "みぎがわ", "meaning": "Bên phải" },
    { "id": 849, "kanji": "通路", "hiragana": "つうろ", "meaning": "Lối đi" },
    { "id": 850, "kanji": "道路", "hiragana": "どうろ", "meaning": "Đường bộ, con đường" },
    { "id": 851, "kanji": "線路", "hiragana": "せんろ", "meaning": "Đường ray" },
    { "id": 852, "kanji": "停止", "hiragana": "ていし", "meaning": "Dừng xe" },
    { "id": 853, "kanji": "バス停", "hiragana": "バスてい", "meaning": "Trạm xe buýt" },
    { "id": 854, "kanji": "整理", "hiragana": "せいり", "meaning": "Sắp xếp, dọn dẹp" },
    { "id": 855, "kanji": "整理券", "hiragana": "せいりけん", "meaning": "Vé ghi số thứ tự" },
    { "id": 856, "kanji": "駐車券", "hiragana": "ちゅうしゃけん", "meaning": "Vé đỗ xe" },
    { "id": 857, "kanji": "乗車券", "hiragana": "じょうしゃけん", "meaning": "Vé lên tàu xe" },
    { "id": 858, "kanji": "回数券", "hiragana": "かいすうけん", "meaning": "Vé tập (dành cho nhiều lần đi)" },
    { "id": 859, "kanji": "現金", "hiragana": "げんきん", "meaning": "Tiền mặt" },
    { "id": 860, "kanji": "表現", "hiragana": "ひょうげん", "meaning": "Diễn đạt, biểu hiện" },
    { "id": 861, "kanji": "現れる", "hiragana": "あらわれる", "meaning": "Hiện ra, xuất hiện" },
    { "id": 862, "kanji": "両親", "hiragana": "りょうしん", "meaning": "Bố mẹ" },
    { "id": 863, "kanji": "両替", "hiragana": "りょうがえ", "meaning": "Đổi tiền" },
    { "id": 864, "kanji": "取り替える", "hiragana": "とりかえる", "meaning": "Thay thế, đổi" },
    { "id": 865, "kanji": "着替える", "hiragana": "きがえる", "meaning": "Thay quần áo" },
    { "id": 866, "kanji": "優先席", "hiragana": "ゆうせんせき", "meaning": "Chỗ ngồi ưu tiên" },
    { "id": 867, "kanji": "優しい", "hiragana": "やさしい", "meaning": "Dịu dàng, tốt bụng" },
    { "id": 868, "kanji": "女優", "hiragana": "じょゆう", "meaning": "Nữ diễn viên" },
    { "id": 869, "kanji": "座席", "hiragana": "ざせき", "meaning": "Chỗ ngồi" },
    { "id": 870, "kanji": "座る", "hiragana": "すわる", "meaning": "Ngồi" },
    { "id": 871, "kanji": "降車口", "hiragana": "こうしゃぐち", "meaning": "Cửa xuống xe" },
    { "id": 872, "kanji": "降りる", "hiragana": "おりる", "meaning": "Xuống xe" },
    { "id": 873, "kanji": "降る", "hiragana": "ふる", "meaning": "Rơi (mưa, tuyết)" }
];